# Generated by Django 4.2.4 on 2023-09-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_course', models.CharField(max_length=50, verbose_name='название курса')),
                ('preview_course', models.ImageField(blank=True, null=True, upload_to='Course/', verbose_name='изображение')),
                ('description', models.TextField(verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_lesson', models.CharField(max_length=50, verbose_name='название урока')),
                ('description', models.TextField(verbose_name='описание')),
                ('preview_lesson', models.ImageField(blank=True, null=True, upload_to='Lesson/', verbose_name='изображение')),
                ('link_video', models.URLField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ('id',),
            },
        ),
    ]
