# Generated by Django 4.2.4 on 2023-09-06 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.course', verbose_name='курс'),
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=50, verbose_name='студент')),
                ('date_payment', models.PositiveSmallIntegerField(verbose_name='дата платежа')),
                ('amount_payment', models.PositiveIntegerField(verbose_name='сумма оплаты')),
                ('method_payment', models.CharField(choices=[('spot', 'Наличный'), ('cashless', 'Безналичный')], max_length=35, verbose_name='способ оплаты: наличные или перевод на счет')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.course', verbose_name='курс')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.lesson', verbose_name='урок')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'ordering': ('-date_payment',),
            },
        ),
    ]
