# Generated by Django 4.2.4 on 2023-09-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_alter_lesson_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='date_payment',
            field=models.CharField(max_length=35, verbose_name='дата платежа'),
        ),
    ]
